spring:
  application:
    name: admin-client
  security:
    user:
      name: client
      password: client
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file: var/log/sample-boot-application.log
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765